### ISSUE TITLE
Add On zerstört nanogallery2

### ISSUE THREAD

**Issue by pointout** [leo-unglaub/contao-firefox-backend-jumper#5]
Hallo Leo, 
ich habe auf einer Seite eine nanogallery2 laufen. Wenn das AddOn aktiv ist, werden die Bilder falsch dargestellt und der Viewer funktioniert nicht:
https://github.com/nanostudio-org/nanogallery2/issues/80

**Comment by leo-unglaub** [comment]
Meine Extension greift nicht in die aktuelle Seite ein. Daher kann das Rendern der Webseite auch nicht durch meine Extension negativ beeinflust werden. Das Problem muss wo anders liegen, ich tippe auf einen reinen Zufall, dass durch die Deaktivierung der Extension die Webseite wieder funktioniert.

Wenn ich auf die Seite gehe funktioniert alles ohne Probleme, ich tippe da eher auf ein Cache Problem.

**Comment by pointout** [comment]
Danke für die Klarstellung und den Hinweis.
